# Generated by Django 4.2.6 on 2023-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_disponible', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
    ]
