# Generated by Django 4.2.6 on 2023-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(max_length=255),
        ),
    ]
