# Generated by Django 4.2.6 on 2023-12-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_producto_fecha_creacion'),
        ('App3', '0002_alter_pedido_direccion_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='App3.DetallePedido', to='App.producto'),
        ),
    ]
